"""Unified production spine for the RecClaw Research Line."""

from .bl_icf_realization import (
    CompilerBoundMechanismV1,
    CompilerBoundRealizationFailureClassV1,
    CompilerBoundRealizationFailureV1,
    CompilerBoundRealizationResultV1,
    CompilerBoundRealizedCandidateV1,
    MechanismImplementationCompanionV1,
    ProviderMechanismProgramProposalV1,
    bind_materialized_bl_icf_candidate,
    compile_bl_icf_candidate_source,
    implementation_spec_for_compiled_program,
    mechanism_program_from_open_spec,
    parent_binding_for_mechanism_program,
    realize_bl_icf_candidate,
)
from .interfaces import (
    BehaviorProjection,
    ProducerOutcome,
    ResearchContext,
    ResearchLineInterfaceError,
)
from .runtime import (
    IdeaAcquisitionResult,
    InnovationLaneResult,
    InnovationRuntimeInputs,
    MetaResearchInputs,
    MetaResearchResult,
    ResearchRoundResult,
    SearchCandidate,
    activate_promoted_meta_strategy,
    activate_staged_innovation,
    bindings_for_context,
    resolver_environment_for_profile,
    run_research_round,
)
from .replay import OfflineProducerReplayV1, OfflineReplayError
from .search_space_adapter import (
    ConfirmationResolutionKindV1,
    ConfirmationResolutionV1,
    SearchSpaceAdapter,
    SearchSpaceExecutionBindingV1,
)
from .single_round import (
    SingleRoundComposition,
    compose_single_round,
    execute_single_round,
)

__all__ = [
    "CompilerBoundMechanismV1",
    "CompilerBoundRealizationFailureClassV1",
    "CompilerBoundRealizationFailureV1",
    "CompilerBoundRealizationResultV1",
    "CompilerBoundRealizedCandidateV1",
    "MechanismImplementationCompanionV1",
    "ProviderMechanismProgramProposalV1",
    "bind_materialized_bl_icf_candidate",
    "compile_bl_icf_candidate_source",
    "implementation_spec_for_compiled_program",
    "mechanism_program_from_open_spec",
    "parent_binding_for_mechanism_program",
    "realize_bl_icf_candidate",
    "BehaviorProjection",
    "ProducerOutcome",
    "ResearchContext",
    "ResearchLineInterfaceError",
    "IdeaAcquisitionResult",
    "InnovationLaneResult",
    "InnovationRuntimeInputs",
    "MetaResearchInputs",
    "MetaResearchResult",
    "ResearchRoundResult",
    "SearchCandidate",
    "activate_promoted_meta_strategy",
    "activate_staged_innovation",
    "bindings_for_context",
    "resolver_environment_for_profile",
    "run_research_round",
    "OfflineProducerReplayV1",
    "OfflineReplayError",
    "ConfirmationResolutionKindV1",
    "ConfirmationResolutionV1",
    "SearchSpaceAdapter",
    "SearchSpaceExecutionBindingV1",
    "SingleRoundComposition",
    "compose_single_round",
    "execute_single_round",
]
